# Generated by Django 3.0 on 2019-12-02 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tttserver.Player')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(default='IN_PROGRESS', max_length=20)),
                ('cell_1', models.CharField(default='b', max_length=1)),
                ('cell_2', models.CharField(default='b', max_length=1)),
                ('cell_3', models.CharField(default='b', max_length=1)),
                ('cell_4', models.CharField(default='b', max_length=1)),
                ('cell_5', models.CharField(default='b', max_length=1)),
                ('cell_6', models.CharField(default='b', max_length=1)),
                ('cell_7', models.CharField(default='b', max_length=1)),
                ('cell_8', models.CharField(default='b', max_length=1)),
                ('cell_9', models.CharField(default='b', max_length=1)),
                ('player_o', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_o_fk', to='tttserver.Player')),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_x_fk', to='tttserver.Player')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turn_fk', to='tttserver.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner_fk', to='tttserver.Player')),
            ],
        ),
    ]
