# Generated by Django 3.0 on 2019-12-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tttserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='player_o',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_o_fk', to='tttserver.Player'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_x_fk', to='tttserver.Player'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turn_fk', to='tttserver.Player'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner_fk', to='tttserver.Player'),
        ),
    ]
